AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create a VPC with subnets, route tables, and an internet gateway.

VPCNestedStack:
  Type: AWS::CloudFormation::Stack
  Properties:
    TemplateURL: https://s3.amazonaws.com/mybucket/vpc.yaml # Update with your S3 bucket URL
    Parameters:
      VpcCidr: 10.0.0.0/16
      InstanceTenancy: default

SubnetNestedStack:
  Type: AWS::CloudFormation::Stack
  Properties:
    TemplateURL: https://s3.amazonaws.com/mybucket/subnet.yaml # Update with your S3 bucket URL
    Parameters:
      MySubnet1Cidr: 10.0.0.0/20
      MySubnet2Cidr: 10.0.1.0/20
      SubnetAZ: !Select [ 0, !GetAZs '' ]
    DependsOn: VPCNestedStack

InternetGatewayNestedStack:
  Type: AWS::CloudFormation::Stack
  Properties:
    TemplateURL: https://s3.amazonaws.com/mybucket/internetGateway.yaml # Update with your S3 bucket URL
    DependsOn: VPCNestedStack

PublicRouteTableNestedStack:
  Type: AWS::CloudFormation::Stack
  Properties:
    TemplateURL: https://s3.amazonaws.com/mybucket/publicRouteTable.yaml # Update with your S3 bucket URL
    Parameters:
      DestinationCidrBlock: 10.0.0.0/20
    DependsOn: SubnetNestedStack, InternetGatewayNestedStack

PrivateRouteTableNestedStack:
  Type: AWS::CloudFormation::Stack
  Properties:
    TemplateURL: https://s3.amazonaws.com/mybucket/privateRouteTable.yaml # Update with your S3 bucket URL
    Parameters:
      DestinationCidrBlock: 10.0.1.0/20
    DependsOn: SubnetNestedStack
    