AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create a VPC with subnets, route tables, and an internet gateway.

Resources:
  VPCNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml 
      Parameters:
        VpcCidr: 10.0.0.0/16
        InstanceTenancy: default

  SubnetNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./subnet.yaml 
      Parameters:
        MySubnet1Cidr: 10.0.0.0/24
        MySubnet2Cidr: 10.0.1.0/24
        SubnetAZ: !Select [ 0, !GetAZs '' ]
        VpcId: !GetAtt VPCNestedStack.Outputs.VpcId # Importing VPC ID from another stack
    DependsOn: 
      - VPCNestedStack

  InternetGatewayNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./internetGateway.yaml
      Parameters:
        VpcId: !GetAtt VPCNestedStack.Outputs.VpcId # Importing VPC ID from another stack 
    DependsOn: 
      - VPCNestedStack

  PublicRouteTableNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./publicRouteTable.yaml 
      Parameters:
        DestinationCidrBlock: 10.0.0.0/24
        SubnetId: !GetAtt SubnetNestedStack.Outputs.MySubnet1Id
        VpcId: !GetAtt VPCNestedStack.Outputs.VpcId
        GatewayId: !GetAtt InternetGatewayNestedStack.Outputs.MyInternetGatewayId
    DependsOn: 
      - SubnetNestedStack
      - InternetGatewayNestedStack

  PrivateRouteTableNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./privateRouteTable.yaml 
      Parameters:
        DestinationCidrBlock: 10.0.1.0/24
        SubnetId: !GetAtt SubnetNestedStack.Outputs.MySubnet2Id
        VpcId: !GetAtt VPCNestedStack.Outputs.VpcId
    DependsOn: 
      - SubnetNestedStack

  SecurityGroupNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./securityGp.yaml 
      Parameters:
        VpcId: !GetAtt VPCNestedStack.Outputs.VpcId
    DependsOn: 
      - VPCNestedStack

Outputs:
  VpcId:
    Description: The ID of the created VPC
    Value: !GetAtt VPCNestedStack.Outputs.VpcId
    Export:
      Name: NetworkStack-VpcId
  PublicSubnetId:
    Description: The ID of the created Public Subnet
    Value: !GetAtt SubnetNestedStack.Outputs.MySubnet1Id
    Export:
      Name: NetworkStack-PublicSubnetId
  PrivateSubnetId:
    Description: The ID of the created Private Subnet
    Value: !GetAtt SubnetNestedStack.Outputs.MySubnet2Id
    Export:
      Name: NetworkStack-PrivateSubnetId
  InternetGatewayId:
    Description: The ID of the created Internet Gateway 
    Value: !GetAtt InternetGatewayNestedStack.Outputs.MyInternetGatewayId
    Export:
      Name: NetworkStack-InternetGatewayId
  PublicRouteTableId:
    Description: The ID of the created Public Route Table 
    Value: !GetAtt PublicRouteTableNestedStack.Outputs.MyRouteTableId
    Export:
      Name: NetworkStack-PublicRouteTableId
  PrivateRouteTableId:
    Description: The ID of the created Private Route Table  
    Value: !GetAtt PrivateRouteTableNestedStack.Outputs.PrivateRouteTableId
    Export:
      Name: NetworkStack-PrivateRouteTableId
  SecurityGroupId:
    Description: The ID of the created Security Group 
    Value: !GetAtt SecurityGroupNestedStack.Outputs.MySecurityGroupId
    Export:
      Name: NetworkStack-MySecurityGroupId  
