AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create a VPC with subnets, route tables, and an internet gateway.

Resources:
  VPCNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml 
      Parameters:
        VpcCidr: 10.0.0.0/16
        InstanceTenancy: default

  SubnetNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./subnet.yaml 
      Parameters:
        MySubnet1Cidr: 10.0.0.0/24
        MySubnet2Cidr: 10.0.1.0/24
        SubnetAZ: !Select [ 0, !GetAZs '' ]
        VpcId: !GetAtt VPCNestedStack.Outputs.VpcId # Importing VPC ID from another stack
    DependsOn: 
      - VPCNestedStack

  InternetGatewayNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./internetGateway.yaml
      Parameters:
        VpcId: !GetAtt VPCNestedStack.Outputs.VpcId # Importing VPC ID from another stack 
    DependsOn: 
      - VPCNestedStack

  PublicRouteTableNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./publicRouteTable.yaml 
      Parameters:
        DestinationCidrBlock: 10.0.0.0/24
        SubnetId: !GetAtt SubnetNestedStack.Outputs.MySubnet1Id
        VpcId: !GetAtt VPCNestedStack.Outputs.VpcId
        GatewayId: !GetAtt InternetGatewayNestedStack.Outputs.MyInternetGatewayId
    DependsOn: 
      - SubnetNestedStack
      - InternetGatewayNestedStack

  PrivateRouteTableNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./privateRouteTable.yaml 
      Parameters:
        DestinationCidrBlock: 10.0.1.0/24
        SubnetId: !GetAtt SubnetNestedStack.Outputs.MySubnet2Id
        VpcId: !GetAtt VPCNestedStack.Outputs.VpcId
    DependsOn: 
      - SubnetNestedStack
