AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create private route table and associate it with a private subnet.

Parameters:
  DestinationCidrBlock:
    Type: String
    Description: The DestinationCidrBlock for the local route
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC where the route table will be created

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the Private Subnet to associate with the route table

Resources:
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId # Importing VPC ID from another stack
      Tags:
        - Key: Name
          Value: PrivateRouteTable
      
  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetId # Importing Private Subnet ID from another stack
      RouteTableId: !Ref PrivateRouteTable

Outputs:
  PrivateRouteTableId:
    Description: The ID of the created Private Route Table
    Value: !Ref PrivateRouteTable
    