AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create a route table and associate it with a subnet.

Parameters:
  DestinationCidrBlock:
    Type: String
    Description: The DestinationCidrBlock for the local route
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC where the route table will be created
  
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the Public Subnet to associate with the route table

  GatewayId:
    Type: String
    Description: The ID of the Internet Gateway to route traffic to

Resources:
  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId # Importing VPC ID from another stack
      Tags:
        - Key: Name
          Value: MyRouteTable
  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref MyRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref GatewayId # Importing Internet Gateway ID from another stack    
  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetId # Importing Public Subnet ID from another stack
      RouteTableId: !Ref MyRouteTable
Outputs:
  MyRouteTableId:
    Description: The ID of the created Route Table
    Value: !Ref MyRouteTable
    #Export:
      #Name: !Sub "${AWS::StackName}-MyRouteTableId"

  
